# Generated by Django 5.1.4 on 2024-12-28 09:26

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_orders_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='oid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=1),  # Set default value temporarily for migration
        ),
    ]
