# Generated by Django 5.1.4 on 2024-12-28 09:31

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_orders_oid_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.orders'),  # Use default to avoid NULL
            preserve_default=False,
        ),
    ]
