# Generated by Django 5.1.4 on 2024-12-28 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Function to update existing orders with a default user
def set_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')  # Get the User model
    default_user = User.objects.first()  # Get the first user as the default
    
    if default_user:
        Orders = apps.get_model('ecommerceapp', 'Orders')  # Get the Orders model
        Orders.objects.update(user=default_user)  # Set the default user for all orders

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_remove_orders_oid_remove_orderupdate_order_id_and_more'),  # Update this dependency with your previous migration file
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add the 'user' field to the orders table, making it nullable initially
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # Run the function to set a default user for existing orders
        migrations.RunPython(set_default_user),
    ]
